[2025-01-07 10:05:58,835] INFO [Remit_agent.database.get_logger:77] Logger initialized: Remit_agent.database
[2025-01-07 10:05:58,933] INFO [Remit_agent.tools.tool_monitoring.get_logger:77] Logger initialized: Remit_agent.tools.tool_monitoring
[2025-01-07 10:05:59,766] INFO [Remit_agent.tools.tools.get_logger:77] Logger initialized: Remit_agent.tools.tools
[2025-01-07 10:06:00,423] INFO [Remit_agent.core.sql_agent.get_logger:77] Logger initialized: Remit_agent.core.sql_agent
[2025-01-07 10:06:00,423] INFO [__main__.get_logger:77] Logger initialized: __main__
[2025-01-07 10:06:01,133] INFO [Remit_agent.core.sql_agent.__init__:35] Initializing SQL Agent...
[2025-01-07 10:06:02,473] INFO [Remit_agent.database.receive_connect:37] New database connection established
[2025-01-07 10:06:02,558] INFO [Remit_agent.core.sql_agent.__init__:42] Database connection successful
[2025-01-07 10:06:02,639] INFO [Remit_agent.core.sql_agent.__init__:47] SQL Agent initialized successfully
[2025-01-07 10:06:06,667] INFO [__main__.main:239] Processing question: give me the customer with highest transaction amount
[2025-01-07 10:06:06,667] INFO [Remit_agent.core.sql_agent.run:173] Starting workflow with question: give me the customer with highest transaction amount
[2025-01-07 10:06:06,762] ERROR [Remit_agent.core.sql_agent._check_relevance:58] Error in relevance check: 1 validation error for check_relevance
input_dict
  Input should be a valid dictionary [type=dict_type, input_value='give me the customer wit...hest transaction amount', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/dict_type
